Figma portfolio by using of html and css
VivekRaaZ/Raj--Portfolio pull request #1
Opened 2023-02-18 17:53 UTC by VivekRaaZ

my first figma portfolio, figma make easy software developer work.

2023-02-18 19:12 UTC, RaoAkif requested changes
## STATUS: REQUIRED CHANGES ♻️

Hi @VivekRaaZ, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
✔ Linters are on point 
✔ Splendid work with the README file
✔ Great use of GitHub flow
✔ Good code design and implementation

## Required Changes ♻️
_Check the comments under the review._
<img src="https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966" />

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-18 19:12 UTC, RaoAkif commented on index.html
> + <body>
The ratio of your design dimensions is perfect. But this design must fit the screen of a mobile.
This is what I can see on the screen
![image](https://user-images.githubusercontent.com/61361037/219883288-fa8ec09a-510a-4117-9451-3a2ec0e16e70.png)

Your portfolio design is supposed to be matching with the Figma design.
To achieve this:
1. Remove `border: 5px solid palevioletred;`
2. Add/Update `margin-left: 0px;`  `margin-right: 0px;` to the `.rj`

![image](https://user-images.githubusercontent.com/61361037/219883378-6b851da6-a2f7-4d04-9b9e-533d3dcc3c8b.png)

2023-02-18 19:12 UTC, RaoAkif commented on index.html
> +    <h1>Hey There. I'm Vivek Raj glad to see you!</h1>
The size of this headline `<h1>Hey There. I'm Vivek Raj glad to see you!</h1>` in your design is `1.5em`, which is very small as compared to the one given in Figma design i.e. `font-size: 40px;`

2023-02-18 19:12 UTC, RaoAkif commented on index.html
> +          <h5 class="connect">LET'S CONNECT</h5>
The design of this element is quite different from the one provided in Figma. You have used the following style for this element.
```
color: blueviolet;
 font-size: 20px;
 font-family: Arial, Helvetica, sans-serif;
```
The actual styling is:
```
font-family: 'Poppins';
font-size: 16px;
color: #7F8CFF;
```

2023-02-18 19:12 UTC, RaoAkif commented on index.html
> +          </ul>
The social media icons are in your design are a little bit in the centre. But in Figma design they are aligned left. Kindly see the comparison below and try to follow the Figma design:
| Your Design   | FIGMA Design  |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/61361037/219883767-2f32c35d-58d0-40dd-958a-616de1b9a346.png)| ![image](https://user-images.githubusercontent.com/61361037/219883755-ce4d687b-bd44-424d-af90-0826db7ad761.png)|

2023-02-18 19:12 UTC, RaoAkif commented on index.html
> +  </section>
After resolving the above-suggested issues, kindly readjust the background image, The comparison is given below:
| Your Design   | FIGMA Design  |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/61361037/219883899-d665fb0b-c1fb-4bb3-b6f2-d0e5147f5963.png)| ![image](https://user-images.githubusercontent.com/61361037/219883878-f7a81df8-df8c-45bf-acc2-c6790732eafa.png)|

2023-02-21 10:39 UTC, mukhammadrizooff requested changes
.

2023-02-21 10:40 UTC, mukhammadrizooff requested changes
Hi @VivekRaaZ, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- No linter errors ✔️ 
- Good implementations ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- [ ] [OPTIONAL] Please add more information about your project to your `Pull Request` description 🙏🏼 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-21 10:40 UTC, mukhammadrizooff commented on style.css
> +* {
- [REQUIRED] Good job so far! Please remove `unnecessary` white space like a [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122&t=UcPq91N1XFqxbjD6-0) 🙏🏼 

![image](https://user-images.githubusercontent.com/63915024/220321531-be26fbc5-b44a-4674-a954-ef2b457e0176.png)

2023-02-24 12:40 UTC, IngDavidTM approved these changes
Hi @VivekRaaZ 🙋‍♂️, 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations!  🎉💯🌟 

## Top highlight 🎯

- The Pull Request follows the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 
<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-24 15:37 UTC, merged

2023-02-24 15:37 UTC, VivekRaaZ commented
Raj portfolio with figma design